---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: packages
      block:
        - name: install required packages
          dnf:
            name: "{{ packages }}"
            state: present
          when: packages is defined

        - name: remove packages
          dnf:
            name: "{{ absent_packages }}"
            state: absent
          when: absent_packages is defined
      tags:
        - packages

    - name: locale, time ...
      block:
        - name: setup time
          file:
            state: link
            force: yes
            src: "/usr/share/zoneinfo/{{ timezone }}"
            dest: /etc/localtime
            owner: root
            group: root
            mode: 0644

        - name: setup locale.conf
          template:
            src: locale.conf.j2
            dest: /etc/locale.conf
            owner: root
            group: root
            mode: 0644
      tags:
        - locale

    - name: networking
      block:
        - name: setup hostname
          hostname:
            name: "{{ hostname }}"
            use: systemd
          notify: restart nm

        - name: create /etc/systemd/system-preset directory
          file:
            path: /etc/systemd/system-preset
            state: directory
            owner: root
            group: root
            mode: 0755

        - name: opt out of systemd-resolved use
          copy:
            dest: /etc/systemd/system-preset/20-systemd-resolved-disable.preset
            content: "disable systemd-resolved.service"
            owner: root
            group: root
            mode: 0644
          notify: daemon-reload

        - name: setup NetworkManager
          template:
            src: NetworkManager.conf.j2
            dest: /etc/NetworkManager/NetworkManager.conf
            owner: root
            group: root
            mode: 0644
          notify: restart nm

        - name: setup /etc/hosts
          template:
            src: hosts.j2
            dest: /etc/hosts
            owner: root
            group: root
            mode: 0644
          notify: restart nm

        - name: setup resolv.conf
          template:
            src: resolv.conf.j2
            dest: /etc/resolv.conf
            owner: root
            group: root
            mode: 0644
          notify: restart nm
      tags:
        - network

    - name: firewall
      block:
        - name: setup iptables rules
          template:
            src: iptables-rules.j2
            dest: /usr/local/sbin/iptables-rules
            owner: root
            group: root
            mode: 0700
          notify: restart iptables

        - name: setup iptables service
          template:
            src: iptables.service.j2
            dest: /etc/systemd/system/iptables.service
            owner: root
            group: root
            mode: 0644
          notify:
            - daemon-reload
            - restart iptables
      tags:
        - firewall

    - name: fonts
      block:
        - name: setup fontconfig
          template:
            src: fontconfig.j2
            dest: /etc/fonts/local.conf
            owner: root
            group: root
            mode: 0644
          notify: run fc-cache

        - name: setup fontconfig symlinks
          file:
            state: link
            force: yes
            src: "/usr/share/fontconfig/conf.avail/{{ item }}"
            dest: "/etc/fonts/conf.d/{{ item }}"
            owner: root
            group: root
            mode: 0644
          loop: "{{ fontconfig_symlinks }}"
          notify: run fc-cache
          when: fontconfig_symlinks is defined
      tags:
        - fonts

    - name: gnome shell
      block:
        - name: setup font and theme and perform few other tweaks on gnome shell
          become: yes
          become_user: "{{ user }}"
          dconf:
            key: "{{ item.key }}"
            value: "{{ item.value }}"
            state: present
          loop: "{{ gnome_dconf_settings }}"
          when: gnome_dconf_settings is defined

        - name: remove desktop icons
          file:
            path: "/usr/share/applications/{{ item }}"
            state: absent
          loop: "{{ absent_desktop_icons }}"
          when: absent_desktop_icons is defined
      tags:
        - gnome

    - name: set sysctl values
      sysctl:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop: "{{ sysctl_values }}"
      when: sysctl_values is defined
      tags:
        - sysctl

    - name: setup environment variables
      lineinfile:
        line: "{{ item }}"
        path: /etc/environment
      loop: "{{ environment_vars }}"
      when: environment_vars is defined
      tags:
        - environment

    - name: k8s
      block:
        - name: install minikube
          dnf:
            name: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
            state: present
      tags:
        - k8s

    - name: docker
      block:
        - name: setup docker repository
          command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
          args:
            creates: /etc/yum.repos.d/docker-ce.repo

        - name: install docker packages
          dnf:
            name: ["docker-ce", "docker-ce-cli", "containerd.io"]
            state: present
            update_cache: yes
      tags:
        - docker

    - name: system services
      block:
        - name: ensure critical system services are running
          systemd:
            name: "{{ item }}"
            state: started
            enabled: yes
          loop: "{{ critical_system_services }}"
          when: critical_system_services is defined

        - name: mask unwanted system services
          systemd:
            name: "{{ item }}"
            state: stopped
            masked: yes
          loop: "{{ masked_system_services }}"
          when: masked_system_services is defined
      tags:
        - services

    - name: user services
      block:
        - name: ensure critical user services are running
          systemd:
            name: "{{ item }}"
            scope: user
            enabled: yes
            state: started
          loop: "{{ critical_user_services }}"
          when: critical_user_services is defined

        - name: mask unwanted user services
          systemd:
            name: "{{ item }}"
            scope: user
            masked: yes
            state: stopped
          loop: "{{ masked_user_services }}"
          when: masked_user_services is defined
      become: yes
      become_user: "{{ user }}"
      tags:
        - user_services

    - name: vim
      block:
        - name: prepare vim plug directories
          file:
            path: "{{ item }}"
            state: directory
            recurse: yes
          loop:
            - /home/{{ user }}/.vim/autoload
            - /home/{{ user }}/.vim/plugged

        - name: install vim-plug
          get_url:
            url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
            dest: "{{ item  }}"
            owner: "{{ user }}"
            group: "{{ user }}"
          when: not ansible_check_mode
          loop:
            - /home/{{ user }}/.vim/autoload/plug.vim

        - name: put plugins into plugged directory
          git:
            repo: "{{ item }}"
            dest: "/home/{{ user }}/.vim/plugged/{{ item.split('/')[4] }}"
            update: yes
            force: yes
            depth: 1
          when: vim_plugins is defined and not ansible_check_mode
          loop: "{{ vim_plugins }}"

        - name: setup vimrc
          template:
            src: vimrc.j2
            dest: "/home/{{ user }}/.vimrc"
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: 0644
      become: yes
      become_user: "{{ user }}"
      tags:
        - vim

    - name: provision dotfiles
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: 0644
      loop:
        - { src: "gitconfig.j2", dest: "/home/{{ user }}/.gitconfig", owner: "{{ user }}", group: "{{ user }}" }
        - { src: "zshrc.j2", dest: "/home/{{ user }}/.zshrc", owner: "{{ user }}", group: "{{ user }}" }
      tags:
        - dotfiles

  handlers:
    - name: run fc-cache
      command: fc-cache -r

    - name: daemon-reload
      systemd:
        daemon-reload: yes

    - name: restart nm
      systemd:
        name: NetworkManager
        state: restarted

    - name: restart iptables
      systemd:
        name: iptables
        state: restarted
